# Voorbeeldconfiguratie Connectix Slimme meter WiFi gateway
# Berekening gasverbruik en electriciteitsverbruik per uur
sensor:
  - platform: dsmr_reader
  - platform: mqtt
    name: "Gasverbruik per uur"
    state_topic: "dsmr/reading/gas_hourly_usage"
    unit_of_measurement: 'm3'
  - platform: mqtt
    name: "Electriciteitsverbruik per uur"
    state_topic: "dsmr/reading/electricity_hourly_usage"
    unit_of_measurement: 'kW'
  - platform: mqtt
    name: "MAC Adres"
    state_topic: "dsmr/smart_gateways/mac_address"
  - platform: mqtt
    name: "Firmware versie van gateway"
    state_topic: "dsmr/smart_gateways/running_firmware_version"
  - platform: mqtt
    name: "Beschikbare firmware versie"
    state_topic: "dsmr/smart_gateways/available_firmware_version"
  - platform: mqtt
    name: "Firmware update beschikbaar"
    state_topic: "dsmr/smart_gateways/update_available"
  - platform: mqtt
    name: "WiFi Signaalsterkte (rssi)"
    state_topic: "dsmr/smart_gateways/wifi_rssi"
    unit_of_measurement: 'dB'
  - platform: mqtt
    name: "Connectix P1 to WiFi startup time"
    state_topic: "dsmr/smart_gateways/startup_time"

# Berekening gasverbruik en electriciteitsverbruik per dag en maand (totalen, dus som van hoog- en laagtarief)
  - platform: template
    sensors:
      daily_energy_delivered:
        friendly_name: Daily Energy Delivered
        unit_of_measurement: kWh
        value_template: "{{ (states('sensor.daily_energy_delivered_offpeak')|float + states('sensor.daily_energy_delivered_peak')|float | round(2)) }}"
      monthly_energy_delivered:
        friendly_name: Monthly Energy Delivered
        unit_of_measurement: kWh
        value_template: "{{ (states('sensor.monthly_energy_delivered_offpeak')|float + states('sensor.monthly_energy_delivered_peak')|float | round(2)) }}"
      daily_energy_returned:
        friendly_name: Daily Energy Returned
        unit_of_measurement: kWh
        value_template: "{{ (states('sensor.daily_energy_returned_offpeak')|float + states('sensor.daily_energy_returned_peak')|float | round(2)) }}"
      monthly_energy_returned:
        friendly_name: Monthly Energy Returned
        unit_of_measurement: kWh
        value_template: "{{ (states('sensor.monthly_energy_returned_offpeak')|float + states('sensor.monthly_energy_returned_peak')|float | round(2)) }}"
      hourly_energy_returned:
        friendly_name: Hourly Energy Returned
        unit_of_measurement: kWh
        value_template: "{{ (states('sensor.hourly_energy_returned_offpeak')|float + states('sensor.hourly_energy_returned_peak')|float | round(2)) }}"


# Berekening van uurwaarden voor electriciteit hoog- en laagtarief
utility_meter:
  hourly_energy_delivered_offpeak:
    source: sensor.dsmr_reading_electricity_delivered_1
    cycle: hourly
  hourly_energy_delivered_peak:
    source: sensor.dsmr_reading_electricity_delivered_2
    cycle: hourly

  hourly_energy_returned_offpeak:
    source: sensor.dsmr_reading_electricity_returned_1
    cycle: hourly
  hourly_energy_returned_peak:
    source: sensor.dsmr_reading_electricity_returned_2
    cycle: hourly

# Berekening van dagwaarden voor electriciteit hoog- en laagtarief
  daily_energy_delivered_offpeak:
    source: sensor.dsmr_reading_electricity_delivered_1
    cycle: daily
  daily_energy_delivered_peak:
    source: sensor.dsmr_reading_electricity_delivered_2
    cycle: daily

  daily_energy_returned_offpeak:
    source: sensor.dsmr_reading_electricity_returned_1
    cycle: daily
  daily_energy_returned_peak:
    source: sensor.dsmr_reading_electricity_returned_2
    cycle: daily

# Berekening van maandwaarden voor electriciteit hoog- en laagtarief
  monthly_energy_delivered_offpeak:
    source: sensor.dsmr_reading_electricity_delivered_1
    cycle: monthly
  monthly_energy_delivered_peak:
    source: sensor.dsmr_reading_electricity_delivered_2
    cycle: monthly

  monthly_energy_returned_offpeak:
    source: sensor.dsmr_reading_electricity_returned_1
    cycle: monthly
  monthly_energy_returned_peak:
    source: sensor.dsmr_reading_electricity_returned_2
    cycle: monthly

# Berekening van dag- en maandwaarden voor gas
  daily_gas:
    source: sensor.dsmr_consumption_gas_delivered
    cycle: daily

  monthly_gas:
    source: sensor.dsmr_consumption_gas_delivered
    cycle: monthly


switch:
  - platform: mqtt
    name: "Install firmware update?"
    command_topic: "dsmr/smart_gateways/install_update"
    payload_on: "yes"
    payload_off: "no"